### ISSUE TITLE
RunestoneServer event database example

### ISSUE THREAD

**Issue by Adonais0** [tl-its-umich-edu/RunestoneServer#7]
RunestoneServer is able to track user's viewing history with the URL pattern `runestone/BOOK/CHAPTER/SUBCHAPTER.html`

See details of the `useinfo` table below: 

<img width="1061" alt="screen shot 2019-01-15 at 3 58 42 pm" src="https://user-images.githubusercontent.com/31697300/51209783-0e684980-18df-11e9-9d21-ad75cf62b0c5.png">

**Comment by jonespm** [comment]
Let me know if you see any other events. It looks like most of them are assessment. I think if we track this page.view first it will be a good start
